# Pull base image
FROM amd64/debian:jessie

# Add our user and group first to make sure their 
# IDs get assigned consistently, regardless of 
# whatever dependencies get added.
RUN groupadd -r mongodb && useradd -r -g mongodb mongodb

# Install MongoDB on debian image
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 9DA31620334BD75D9DCB49F368818C72E52529D4 \
    && echo "deb http://repo.mongodb.org/apt/debian jessie/mongodb-org/4.0 main" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list \
    && apt-get update \
    && apt-get install -y mongodb-org \
    && rm -rf /var/lib/mongodb

# Define working directory.
WORKDIR /data

# Configuration.
RUN mkdir -p /data/db /data/configdb \
    && chown -R mongodb:mongodb /data/db /data/configdb

# Define mountable directories.
VOLUME /data/db /data/configdb

# Expose ports.
#   - 27017: process
#   - 28017: http
EXPOSE 27017 28017

# Define default command.
# command for debian
CMD ["mongod", "--bind_ip_all"]